var channelData = {
    "data": [
        {
            "dayRange": "20170822",
            "timeRange": "00:00-01:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7797,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2216882,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "000000",
            "stopTime": "010000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "00:00-01:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0766,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 217862,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "000000",
            "stopTime": "010000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "00:00-01:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0639,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 181636,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "000000",
            "stopTime": "010000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "00:00-01:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.038,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 108162,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "000000",
            "stopTime": "010000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "01:00-02:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.775,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2203385,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "010000",
            "stopTime": "020000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "01:00-02:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.071,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 201992,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "010000",
            "stopTime": "020000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "01:00-02:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0627,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 178173,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "010000",
            "stopTime": "020000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "01:00-02:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0385,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 109484,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "010000",
            "stopTime": "020000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "02:00-03:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7664,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2178851,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "020000",
            "stopTime": "030000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "02:00-03:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0698,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 198326,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "020000",
            "stopTime": "030000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "02:00-03:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0632,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 179550,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "020000",
            "stopTime": "030000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "02:00-03:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0374,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 106337,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "020000",
            "stopTime": "030000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "03:00-04:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7607,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2162666,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "030000",
            "stopTime": "040000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "03:00-04:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.069,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 196136,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "030000",
            "stopTime": "040000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "03:00-04:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0623,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 177155,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "030000",
            "stopTime": "040000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "03:00-04:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0378,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 107603,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "030000",
            "stopTime": "040000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "04:00-05:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7557,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2148648,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "040000",
            "stopTime": "050000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "04:00-05:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0687,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 195389,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "040000",
            "stopTime": "050000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "04:00-05:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0619,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 175939,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "040000",
            "stopTime": "050000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "04:00-05:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0379,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 107708,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "040000",
            "stopTime": "050000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "05:00-06:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7564,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2150482,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "050000",
            "stopTime": "060000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "05:00-06:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0686,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 194945,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "050000",
            "stopTime": "060000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "05:00-06:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0615,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 174739,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "050000",
            "stopTime": "060000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "05:00-06:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0377,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 107070,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "050000",
            "stopTime": "060000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "06:00-07:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7422,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2110276,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "060000",
            "stopTime": "070000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "06:00-07:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0676,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 192067,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "060000",
            "stopTime": "070000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "06:00-07:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0612,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 174073,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "060000",
            "stopTime": "070000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "06:00-07:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0366,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 103920,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "060000",
            "stopTime": "070000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "07:00-08:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7228,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2054908,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "070000",
            "stopTime": "080000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "07:00-08:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0739,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 210181,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "070000",
            "stopTime": "080000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "07:00-08:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0593,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 168504,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "070000",
            "stopTime": "080000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "07:00-08:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0365,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 103851,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "070000",
            "stopTime": "080000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "08:00-09:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.6737,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 1915405,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "080000",
            "stopTime": "090000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "08:00-09:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1136,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 323020,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "080000",
            "stopTime": "090000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "08:00-09:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0645,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 183493,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "080000",
            "stopTime": "090000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "08:00-09:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0388,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 110374,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "080000",
            "stopTime": "090000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "09:00-10:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7233,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2056372,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "090000",
            "stopTime": "100000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "09:00-10:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.143,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 406483,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "090000",
            "stopTime": "100000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "09:00-10:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0727,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 206643,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "090000",
            "stopTime": "100000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "09:00-10:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0491,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 139700,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "090000",
            "stopTime": "100000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "10:00-11:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7713,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2192925,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "100000",
            "stopTime": "110000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "10:00-11:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1672,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 475420,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "100000",
            "stopTime": "110000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "10:00-11:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0777,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 221048,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "100000",
            "stopTime": "110000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "10:00-11:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0584,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 166140,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "100000",
            "stopTime": "110000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "11:00-12:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.8219,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2336646,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "110000",
            "stopTime": "120000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "11:00-12:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.177,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 503236,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "110000",
            "stopTime": "120000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "11:00-12:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1035,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 294275,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "110000",
            "stopTime": "120000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "11:00-12:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0602,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 171264,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "110000",
            "stopTime": "120000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "12:00-13:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.6744,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 1917350,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "120000",
            "stopTime": "130000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "12:00-13:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.2094,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 595372,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "120000",
            "stopTime": "130000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "12:00-13:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1253,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 356376,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "120000",
            "stopTime": "130000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "12:00-13:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0422,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 120051,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "120000",
            "stopTime": "130000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "13:00-14:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.689,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 1958829,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "130000",
            "stopTime": "140000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "13:00-14:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1868,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 531028,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "130000",
            "stopTime": "140000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "13:00-14:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0751,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 213412,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "130000",
            "stopTime": "140000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "13:00-14:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0561,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 159576,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "130000",
            "stopTime": "140000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "14:00-15:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7037,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2000780,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "140000",
            "stopTime": "150000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "14:00-15:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1567,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 445549,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "140000",
            "stopTime": "150000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "14:00-15:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0939,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 267068,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "140000",
            "stopTime": "150000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "14:00-15:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0599,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 170413,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "140000",
            "stopTime": "150000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "15:00-16:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7282,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2070435,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "150000",
            "stopTime": "160000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "15:00-16:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1442,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 410063,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "150000",
            "stopTime": "160000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "15:00-16:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1015,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 288644,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "150000",
            "stopTime": "160000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "15:00-16:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0608,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 172722,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "150000",
            "stopTime": "160000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "16:00-17:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.7806,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2219274,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "160000",
            "stopTime": "170000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "16:00-17:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.179,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 509017,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "160000",
            "stopTime": "170000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "16:00-17:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1098,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 312254,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "160000",
            "stopTime": "170000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "16:00-17:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0629,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 178749,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "160000",
            "stopTime": "170000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "17:00-18:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.774,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2200522,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "170000",
            "stopTime": "180000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "17:00-18:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1339,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 380598,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "170000",
            "stopTime": "180000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "17:00-18:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1156,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 328628,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "170000",
            "stopTime": "180000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "17:00-18:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.056,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 159180,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "170000",
            "stopTime": "180000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "18:00-19:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 1.0511,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2988529,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "180000",
            "stopTime": "190000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "18:00-19:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0869,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 247204,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "180000",
            "stopTime": "190000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "18:00-19:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0643,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 182800,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "180000",
            "stopTime": "190000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "18:00-19:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0435,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 123584,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "180000",
            "stopTime": "190000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "19:00-20:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 1.2939,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 3678619,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "190000",
            "stopTime": "200000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "19:00-20:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0881,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 250398,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "190000",
            "stopTime": "200000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "19:00-20:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.08,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 227311,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "190000",
            "stopTime": "200000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "19:00-20:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0655,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 186326,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "190000",
            "stopTime": "200000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "20:00-21:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 1.1306,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 3214456,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "200000",
            "stopTime": "210000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "20:00-21:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1638,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 465735,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "200000",
            "stopTime": "210000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "20:00-21:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.123,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 349765,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "200000",
            "stopTime": "210000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "20:00-21:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1075,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 305729,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "200000",
            "stopTime": "210000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "21:00-22:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 1.1437,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 3251677,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "210000",
            "stopTime": "220000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "21:00-22:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1324,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 376317,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "210000",
            "stopTime": "220000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "21:00-22:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1008,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 286538,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "210000",
            "stopTime": "220000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "21:00-22:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.068,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 193467,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "210000",
            "stopTime": "220000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "22:00-23:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.9529,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2709153,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "220000",
            "stopTime": "230000",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "22:00-23:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.1124,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 319586,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "220000",
            "stopTime": "230000",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "22:00-23:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0741,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 210794,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "220000",
            "stopTime": "230000",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "22:00-23:00",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0423,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 120169,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "220000",
            "stopTime": "230000",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "23:00-23:59",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c090",
            "channelName": "湖南卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.8575,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 2437317,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "230000",
            "stopTime": "235959",
            "areaCode": "14300",
            "currentRanking": 1,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "23:00-23:59",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c141",
            "channelName": "浙江卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0947,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 269217,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "230000",
            "stopTime": "235959",
            "areaCode": "14300",
            "currentRanking": 2,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "23:00-23:59",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c098",
            "channelName": "江苏卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0566,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 160878,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "230000",
            "stopTime": "235959",
            "areaCode": "14300",
            "currentRanking": 3,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        },
        {
            "dayRange": "20170822",
            "timeRange": "23:00-23:59",
            "areaName": "湖南",
            "operatorName": "湖南电信",
            "sourceTypeName": "ALL",
            "channelCode": "c055",
            "channelName": "东方卫视",
            "channelGroupCode": "SWPD",
            "channelGroupName": "省外频道",
            "programName": null,
            "audienceRating": 0.0393,
            "marketShare": null,
            "stbNum": null,
            "arrivalRate": null,
            "viewTime": 111825,
            "playTime": null,
            "operator": "HNDX",
            "sourceType": "HNDX_ALL",
            "startTime": "230000",
            "stopTime": "235959",
            "areaCode": "14300",
            "currentRanking": 4,
            "startDay": "20170822",
            "stopDay": "20170822",
            "stbNumErrorMessageSet": [
                "20170822日使用的是20170725日的机顶盒数"
            ]
        }
    ],
    "success": true,
    "errorMessage": "20170822日使用的是20170725日的机顶盒数",
    "errorCode": 0,
    "pageInfo": {
        "currentPage": 1,
        "currentMaxItemLength": 5000,
        "total": 96,
        "time": 0
    },
    "messageTip": null,
    "otherData": null
}